splash = false

wallpaper {
    monitor =
    # path = /usr/share/wallpapers/openSUSEdefault/contents/images/default-dark.png
    path = /home/victor/Pictures/wallpapers/
    fit_mode = cover
    timeout = 300
}
