# HYPRLAND CONFIGURATION

# Source modular components
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/looks.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/autostart.conf

# Window Rules (Basic)
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/custom.conf
