# See https://wiki.hypr.land/Configuring/Environment-variables/
env = GDK_BACKEND,wayland,x11,*
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = XCURSOR_THEME,breeze_cursors
env = GTK_ICON_THEME,Papirus-Dark
env = TERMINAL,kitty

# LibreOffice — use GTK3 backend (Wayland-native, avoids X11 error)
env = SAL_USE_VCLPLUGIN,gtk3
