# See https://wiki.hypr.land/Configuring/Window-Rules/

# Suppress maximize events for all windows
windowrule = match:class .*, suppress_event maximize

# Example: Make specific apps float
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(thunar)$, match:title ^(File Operation Progress)$, float on
windowrule = match:class ^(imv)$, float on, center on
windowrule = match:class ^(mpv)$, float on, center on
windowrule = match:class ^(org.pwmt.zathura)$, float on, center on
windowrule = match:class ^(org.kde.okular)$, float on, center on

# Window-to-workspace assignments
windowrule = workspace 1, match:class ^(google-chrome)$
# windowrule = workspace 2, match:class ^(thunar)$
windowrule = workspace 3, match:class ^(Slack)$
# windowrule = workspace 3, match:class ^(Spotify)$
# windowrule = workspace 4, match:class ^(code-url-handler)$
# windowrule = workspace 4, match:class ^(VSCode)$

